apiVersion: v2
name: imperva-exporter
description: A Prometheus exporter for Imperva Cloud WAF metrics.
type: application
version: 0.1.1
appVersion: "main"
home: https://github.com/wjma90/imperva-exporter
sources:
  - https://github.com/wjma90/imperva-exporter
keywords:
  - imperva
  - prometheus
  - exporter
  - observability
maintainers:
  - name: Willian Marchan
